__Experiment 10: Data Analysis and Visualization__

**Question 1**
📝 Aim

To create a NumPy array and find the sum of all its elements.

__Explanation__

NumPy is a powerful library used for numerical computations in Python. In this program, a NumPy array is created, and the np.sum() function is used to calculate the sum of all the elements efficiently.

In [1]:
import numpy as np

arr = np.array([12, 25, 7, 30, 16])

print("Array:", arr)
print("Sum of all elements:", np.sum(arr))

Array: [12 25  7 30 16]
Sum of all elements: 90


__Question 2__
📝 Aim

To create a 3 × 3 NumPy array and find the row sums, column sums, and second maximum element.

**Explanation**

The program demonstrates common NumPy operations. It calculates the sum of each row and column using the axis parameter and finds the second largest element by sorting the array values.

In [2]:
import numpy as np

matrix_3x3 = np.array([
    [12, 5, 8],
    [7, 25, 14],
    [3, 19, 11],
])

row_sums = np.sum(matrix_3x3, axis=1)
column_sums = np.sum(matrix_3x3, axis=0)

second_max = np.sort(matrix_3x3, axis=None)[-2]

print("Matrix:\n", matrix_3x3)
print("Row sums:", row_sums)
print("Column sums:", column_sums)
print("Second maximum element:", second_max)

Matrix:
 [[12  5  8]
 [ 7 25 14]
 [ 3 19 11]]
Row sums: [25 46 33]
Column sums: [22 49 33]
Second maximum element: 19


__Question 3__
📝 Aim

To perform matrix multiplication using NumPy.

__Explanation__

Matrix multiplication is a common mathematical operation used in machine learning and data analysis. NumPy performs matrix multiplication efficiently using the @ operator.

In [3]:
import numpy as np

matrix_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

matrix_b = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1],
])

product = matrix_a @ matrix_b

print(product)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


__Question 4__
📝 Aim

To calculate the powers of array elements using Pandas.

__Explanation__

Pandas supports element-wise mathematical operations. Here, every element in one Series is raised to the power of the corresponding element in another Series.

In [4]:
import pandas as pd

base_values = pd.Series([0, 1, 2, 3, 4])
power_values = pd.Series([1, 2, 3, 2, 1])

powered_values = base_values ** power_values

print(powered_values)

0    0
1    1
2    8
3    9
4    4
dtype: int64


__Question 5__
📝 Aim

To display the first three rows of a Pandas DataFrame.

__Explanation__

A DataFrame stores data in a tabular form. The head(3) function returns the first three rows, making it useful for previewing a dataset.

Python Code

Use the same DataFrame (exam_data) provided in your notebook, then execute:

In [8]:
import pandas as pd

exam_df = pd.DataFrame({
    "name": ["Anastasia", "Dima", "Katherine", "James", "Emily"],
    "score": [12.5, 9.0, 16.5, 18.0, 15.5],
    "attempts": [1, 3, 2, 3, 2],
    "qualify": ["Yes", "No", "Yes", "Yes", "Yes"]
})

print(exam_df.head(3))

        name  score  attempts qualify
0  Anastasia   12.5         1     Yes
1       Dima    9.0         3      No
2  Katherine   16.5         2     Yes
